### ISSUE TITLE
About model output

### ISSUE THREAD

**Issue by canhe173** [tlpss/keypoint-detection#19]
Hi, I'm glad to see that you wrote an example of model testing, but I found that the shape of the output of a training model did not conform to the expectation when I referred to the relevant code for testing. Some of my codes are shown as follows:
```python
checkpoint = "./scripts/model.ckpt" 
model = load_from_checkpoint(checkpoint)
model.eval()
heatmaps_train = model(images).detach()
print("heatmaps_train", heatmaps_train.shape)
heatmaps = create_heatmap_batch(shape, keypoints, sigma=6.0, device="cpu")
print("heatmaps_groundtruth", heatmaps.shape)
```
I set the batch-size to 6. The output of the above code is as following. 
![heatmaps_results](https://user-images.githubusercontent.com/97797451/207250560-acb0177d-319e-4140-8d51-771d3b2254c8.png)

**Comment by tlpss** [comment]
@canhe173 the `create_heatmap_batch` function creates the heatmap for a **single** channel. 
As you can see [here](https://github.com/tlpss/keypoint-detection/blob/7905007c60b7676bc508f05323fe1c9e39dfdbd9/keypoint_detection/models/detector.py#L212), you need to iterate over the channels manually.
