### ISSUE TITLE
AP breaks for predictions with same probability

### ISSUE THREAD

**Issue by brambozz** [tlpss/keypoint-detection#41]
Hi!

I'm working on a 2D detection problem (bubble detection in ultrasound) and was looking for an AP implementation which thresholds on distance instead of IoU. Your implementation was exactly that, so thanks!

I noticed if I generate predictions with the same probability, I actually get a PR curve with many points, where I expected only one point. The source is I think [this line](https://github.com/tlpss/keypoint-detection/blob/1507044636a42255338ae81af7cb3c0cdc54ea52/keypoint_detection/models/metrics.py#L129), where points are ordered according to probability. When points have the same probability they will still be ordered randomly, whereas they should be processed as a group and give 1 precision/recall value.

Not sure if this matters in practice though, as predictions maybe never will have exactly the same probability :)

**Comment by tlpss** [comment]
Hi @brambozz, thanks for the feedback!

> Not sure if this matters in practice though, as predictions maybe never will have exactly the same probability :)

Yes I believe the impact is limited as this won't occur (often).

> When points have the same probability they will still be ordered randomly, whereas they should be processed as a group and give 1 precision/recall value.

I had never thought of this edge case actually. But what you are saying makes sense.. I would have to find another implementation of mAP calculation and see how they are handling this (e.g. Coco). If you dig deeper into this, feel free to let me know what you find! Otherwise I will keep it in mind and look into it when I have some time :+1:

**Comment by brambozz** [comment]
Yes, that makes sense! Currently, I think for me it is also not really an issue. I ended up adapting a bit from this repository, because I knew it from a PhD colleague (https://github.com/DIAGNijmegen/picai_eval/tree/main) which uses the sklearn implementation for a similar scenario.

I think in your comments you already said that using that function is an option.

**Comment by tlpss** [comment]
> I think in your comments you already said that using that function is an option.

Yes that seems like a good alternative!
