### ISSUE TITLE
Labelling: support multiple points in CVAT points shape

### ISSUE THREAD

**Issue by Victorlouisdg** [tlpss/keypoint-detection#9]
Currently `get_semantic_type_keypoints_from_instance_in_cvat_image()` expects the `points` field of the `points` tag in `annotations.xml` to only contain a single point. This results in parsing errors when multiple points are specified there e.g. 
```xml
    <points label="towel.corner" occluded="0" source="manual" points="815.71,255.03;1407.78,257.05;773.96,879.93;1443.20,879.93" z_order="0">
    </points>
```

This happens when labeling in CVAT and putting multiple keypoints, e.g. towel corners, into a single `POINTS SHAPE` object.
![image](https://user-images.githubusercontent.com/23340946/192980173-b3ae6eb4-5264-4fc3-b71f-16165032d484.png)

**Comment by tlpss** [comment]
closing since the labeling workflow in this repo is deprecated and will be removed soon. 
You can find the most up-to-date version [here](https://github.com/airo-ugent/airo-mono).
